### ISSUE TITLE
Implement TLS (__thread) support

### ISSUE THREAD

**Issue by mato** [rumpkernel-attic/rumprun-xen#19]
While testing more applications I discovered that we don't have support for TLS, thus application code using `__thread` (among other things) will fault.

Opening this issue to record the changes needed to implement this. Discussion on IRC and reading of the TLS paper by Drepper at http://www.akkadia.org/drepper/tls.pdf suggests that with some creative use of linker-scripts to get at the locations of the `.tbss` and `.tdata` sections in memory implementation should be fairly straightforward (so says @anttikanttee :+1:).

I'm including a simple stress test for TLS which uses both `.tbss` and `.tdata`. Run with a suitable amount of memory (-M 128) for domU.

```c
/* Simple stress-test for TLS support */
#include <err.h>
#include <pthread.h>
#include <stdio.h>

#define NTHREADS 10

static __thread size_t c;
static __thread size_t i = 12345678;

struct thread_info {
    pthread_t id;
    int num;
};

void *thread(void *arg)
{
    struct thread_info *info = (struct thread_info *)arg;
    printf ("Thread %d starting: i = %zd\n", info->num, i);

    c = 0;
    while (c < 1000000) {
        c++;
        pthread_yield();
    }
    return (void *)c;
}

int main(int argc, char *argv[])
{
    int n, rc;
    struct thread_info threads[NTHREADS];

    for (n = 0; n < NTHREADS; n++) {
        threads[n].num = n;
        rc = pthread_create(&threads[n].id, NULL, thread, &threads[n]);
        if (rc != 0) {
            err(1, "pthread_create[%d] failed", n);
        }
    }

    for (n = 0; n < NTHREADS; n++) {
        void *ret;
        rc = pthread_join(threads[n].id, &ret);
        if (rc != 0) {
            err(1, "pthread_join[%d] failed", n);
        }
        printf("Thread %d returned %zd\n", n, (size_t)ret);
    }
    return 0;
}
```

**Comment by anttikantee** [comment]
we're still missing this for x86_32, TBD some day soon

**Comment by anttikantee** [comment]
Fixed ages ago.
