### ISSUE TITLE
Mini-OS threads and stack allocation

### ISSUE THREAD

**Issue by mato** [rumpkernel-attic/rumprun-xen#22]
When testing with PHP I found that the current stack size for a Mini-OS thread is insufficient to serve a single trivial request via FastCGI. The current stack size defined in `minios/x86/limits.h` is 2^4 pages (64kB).
Does anyone have any objections to my increasing the default stack size? Linux on x86[-64] uses a default of 2mB. Given that we don't have a growable stack (see below) we should probably be conservative; my trivial PHP test works with 2^6 pages (256kB).
Second question, what to do about it in the long run? Implement a growable stack?

**Comment by anttikantee** [comment]
No, I don't object to changing it, but 256kB is very fast approaching the acceptable upper limit.

I do not think that we should introduce any assumptions that we're running on top of virtual memory (to keep all rumprun platforms equal), and as such I don't think an on-demand growing stack is acceptable.

However, what we should do is allocate stacks differently for pthread stacks and kernel stacks.  The kernel stacks can deal with a page or two.  That should save several megs of memory right off the bat.

**Comment by mato** [comment]
Related to this, user threads created after calling `pthread_attr_setstacksize()` will cause a crash during thread creation in `_lwp.c` due to the expected and real stack sizes not matching up.

**Comment by anttikantee** [comment]
Right, and fixing that requires minios to get the current thread via some other mechanism than `&var & (STACK_SIZE-1)`.

**Comment by anttikantee** [comment]
This has been fixed ages ago.
